name: Flutter Test and Coverage Report

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"

      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Run tests
        working-directory: frontend
        run: flutter test --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: frontend/coverage/lcov.info
